Add a dependency of the amalgamator
Currently, when importing cdt-amalgamator from other repositories, an error occurs. 
As indicated by "node_modules/cdt-amalgamator/dist/AmalgamatorClient.d.ts(10,29): error TS2307: Cannot find module '@vscode/debugadapter-testsupport' or its corresponding type declarations." in the build output. 
So we need to add a dependency "@vscode/debugadapter-testsupprt" of the amalgamator.